version: "3.3"

services:
  server:
    container_name: encuestas-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "8082:80"
    external_links:
      - mysql-dev:mysql
    networks:
      - contenedores
    environment:
      - "VIRTUAL_HOST=app.encuestas.com"
    expose:
      - 80
networks:
  contenedores:
    external: true
